config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    root to: "crypted_notes#index", as: :authenticated_root

    resources :crypted_notes do
      resources :permitted_contacts do
        get "verify"
        patch "verify_update", to: "verify_update"
        post "request_access", to: "request_access"
        post "reject_access", to: "reject_access"
        get "reject_access"
        post "approve_access", to: "approve_acces"
      end
    end
  end

  get "/crypted_notes/*whatever", to: redirect("/users/sign_in")
  root to: redirect("/users/sign_in")
end

app/models/crypted_note.rb
class CryptedNote < ApplicationRecord
  belongs_to :user
  has_many :crypted_note_parts
  has_many :permitted_contacts

  validates :description, :crypted_content, presence: true

  def backup_code
    file_name = Rails.root.join(*%w[app views crypted_notes _executable_code.erb])
    File.read(file_name).gsub("{{encrypted_content}}", crypted_content)
  end
end

app/controllers/crypted_notes_controller.rb
class CryptedNotesController < ApplicationController
  before_action :set_crypted_note, only: %i[show edit update destroy]

  # GET /crypted_notes or /crypted_notes.json
  def index
    @crypted_notes = current_user.crypted_notes

    permitted_ids = PermittedContact.where(email: current_user.email).pluck(:crypted_note_id)
    @shared_crypted_notes = CryptedNote.where(id: permitted_ids)
  end

  # GET /crypted_notes/1 or /crypted_notes/1.json
  def show
  end

  # GET /crypted_notes/new
  def new
    @crypted_note = current_user.crypted_notes.new
  end

  # GET /crypted_notes/1/edit
  def edit
    @permitted_contact = @crypted_note.permitted_contacts.where(email: current_user.email)

    @permitted_contact&.update(encrypted_content_accessed_at: Time.now)
  end

  # POST /crypted_notes or /crypted_notes.json
  def create
    @crypted_note = current_user.crypted_notes.new(crypted_note_params)

    respond_to do |format|
      if @crypted_note.save
        CryptedNoteMailer.secret_backup_email(@crypted_note).deliver_later

        # format.html { redirect_to crypted_note_url(@crypted_note), notice: "Crypted note was successfully created." }
        format.html { redirect_to crypted_notes_url, notice: "Crypted note was successfully created." }

        format.json { render :show, status: :created, location: @crypted_note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @crypted_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crypted_notes/1 or /crypted_notes/1.json
  def update
    raise "no access" if @crypted_note.user_id != current_user.id

    @crypted_note.update(crypted_note_params)

    CryptedNoteMailer.secret_backup_email(@crypted_note).deliver_later

    redirect_to crypted_notes_url, notice: "Crypted note was successfully updated."
  end

  # DELETE /crypted_notes/1 or /crypted_notes/1.json
  # def destroy
  #   @crypted_note.destroy

  #   respond_to do |format|
  #     format.html { redirect_to crypted_notes_url, notice: "Crypted note was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_crypted_note
    permitted_ids = PermittedContact.where(email: current_user.email).where("decrypt_access_granted_at IS NOT NULL").pluck(:crypted_note_id)

    @crypted_note = CryptedNote.where("user_id = ? or id IN(?)", current_user.id, permitted_ids).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def crypted_note_params
    params.fetch(:crypted_note).permit(:description, :crypted_content, :short_password_hash)
  end
end

app/helpers/crypted_notes_helper.rb
module CryptedNotesHelper
end

app/views/crypted_notes/_code_block.html.erb
<div style="background: black; color: white; border-radius: 10px; font-size:11px; word-wrap: break-word;">
  <div style="background: #333; padding: 10px; border-top-right-radius: 10px; border-top-left-radius: 10px; text-align:right; color: #eee"><code>JavaScript</code></div>
  <code style="padding: 20px 10px; display: block"><%= code %></code>
</div>

app/views/crypted_notes/_code_block_instructions.html.erb
In order to reveal the secret outside of DecLegacy, copy and paste JavasScript code into the browser console and press enter. You can open the console in <em>developer tools &rarr; Javascript Console console</em> or press
<b><code>CTRL + SHIFT + J</code></b> on Linux or Windows, or <b><code>COMMAND + OPTION + J</code></b> on macOS. 
You will be asked for encryption password which will reveal the secret. 

<br/><br/>

<b>We strongly advise you to decrypt the content to ensure that you fully understand how it works.</b><br/> <br/>

app/views/crypted_notes/_crypted_note.html.erb
<div id="<%= dom_id crypted_note %>" class="py-3">
  <% 
    allow_decrypt = crypted_note.user == current_user 
    permitted_contact = nil
    unless allow_decrypt 
      permitted_contact = crypted_note.permitted_contacts.find_by(email: current_user.email)
      allow_decrypt = true if permitted_contact.can_decrypt? 
    end 
  %>

  <div class="flex justify-between">
    <div>
      <%= crypted_note.description %>
      <% if crypted_note.user != current_user %>
        <span class="bg-gray-300 text-gray-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded"><%= crypted_note.user.email %></span>
      <% end %>
    </div>
    
    <div class="">
      <%= link_to "Decrypt", edit_crypted_note_path(crypted_note), class: "btn btn-xs" if allow_decrypt %>
      <% if crypted_note.user == current_user %>
        <%= link_to "Confidant Permissions", crypted_note_permitted_contacts_path(crypted_note), class: "btn btn-xs inline-block" %> 
      <% elsif !permitted_contact.can_decrypt? && !permitted_contact.decrypt_access_requested_at %>
        <%= button_to "Request Decrypt Permission", crypted_note_permitted_contact_request_access_path(crypted_note, permitted_contact), method: :post, class: "btn btn-xs", form: {data: {turbo_confirm: 'Are you sure?'}}   %>
      <% end %>
    </div>
  </div>

  <div>
    <% if crypted_note.user == current_user %>
      <% if crypted_note.permitted_contacts.empty? %>
        <div class="mt-4">
          <%= render 'shared/alert', color: 'orange', title: "Nobody can help you out" do %>
              There are no confidants which could retreive the secret in case of unexpected events.
          <% end %>
        </div>
      <% end %>

      <% reqested_decrypt_contacts = crypted_note.permitted_contacts.where('decrypt_access_requested_at IS NOT NULL') %> 

      <% reqested_decrypt_contacts.each do |c| %>
        <% if c.can_decrypt? %>
          <div class="mt-2">
            <%= render 'shared/alert', color: 'red', title: "Nobody can help you out" do %>
              <%= c.email %> is allowed to decrypt the content since <%= l c.decrypt_access_granted_at.to_date %>.

              <% if c.encrypted_content_accessed_at %>
                  Confidant have ALREADY accessed decrypted content on <%= l c.encrypted_content_accessed_at.to_date%>.
              <% else %>
                  Confidant have NOT yet accessed decrypted content.
              <% end %>
            <% end %>
          </div>
        <% else %>
          <div class="mt-4">
            <%= render "warning" do %>
              <%= c.email %> requested decrypt permission and will gain it <b>automatically</b> on <%= l c.decrypt_access_granted_at.to_date %> unless you reject it</span>
              <div class="mt-4">
                <%= button_to "Reject Access", crypted_note_permitted_contact_reject_access_path(crypted_note, c), method: :post, form: {data: {turbo_confirm: 'Are you sure to reject the access?'}}   %>
                <%= button_to "Approve Access Immediatelly", crypted_note_permitted_contact_approve_access_path(crypted_note, c), method: :post, form: {data: {turbo_confirm: 'Are you sure to grant the access?'}}   %>
              
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <% unless allow_decrypt %>
        <%# link_to "Verify", crypted_note_permitted_contact_verify_path(crypted_note, permitted_contact) %>
        <div class="mt-4">
          <% verify_url = crypted_note_permitted_contact_verify_path(crypted_note, permitted_contact) %>

          <% if permitted_contact.verified_password? %>
            <%= render 'shared/alert', color: 'green', title: "Success" do %>
              Successfully verified that you know the password on <%= l permitted_contact.verified_password_at.to_date %> <%= link_to "Verify again?", verify_url %>
            <% end %>
          <% else %>
            
              <%= render 'shared/alert', color: 'orange', title: "Success" do %>
                  You can verify that you know password without revealing the secret. 

                  <div class="mt-4">
                    <%= link_to "Verify Password?", verify_url, class: 'btn' %>
                  </div>
              <% end %>
          
          <% end %>
         </div>
      <% end %>

      <% if permitted_contact.decrypt_access_requested_at %> 
        <% if permitted_contact.can_decrypt? %>
          
        <% else %>
          <%= render 'shared/alert', color: 'orange', title: "Success" do %>
              Decrypt access is pending and will be auto approved on <%= l permitted_contact.decrypt_access_granted_at.to_date %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
    <%#= link_to "Decrypt", crypted_note %>
  </div>
</div>

app/views/crypted_notes/_crypted_notes.html.erb
  <div class="box-list">
    <% crypted_notes.each do |crypted_note| %>
      <div class="box-list-item"><%= render crypted_note %></div>
    <% end %>
  </div>

app/views/crypted_notes/_executable_code.erb
(async e=>{try{const t=prompt("Decryption Password:"),n=new TextEncoder,o=n.encode(t),[a,c]=e.split(":"),r=new Uint8Array(atob(a).split("").map(e=>e.charCodeAt(0))),i=new Uint8Array(atob(c).split("").map(e=>e.charCodeAt(0))),s=await crypto.subtle.importKey("raw",o,{name:"PBKDF2"},!1,["deriveKey"]),l=await crypto.subtle.deriveKey({name:"PBKDF2",salt:n.encode("salt"),iterations:1e5,hash:"SHA-256"},s,{name:"AES-GCM",length:256},!1,["decrypt"]),p=await crypto.subtle.decrypt({name:"AES-GCM",iv:r},l,i),d=new TextDecoder,u="Decrypted text:\n"+d.decode(p);console.log(u),alert("Decryption successful. Check console output.")}catch(e){alert("Decryption failed. The password may be incorrect.")}})("{{encrypted_content}}");

app/views/crypted_notes/_form.html.erb
<%= form_with(model: crypted_note, data: {controller: "crypted-note"}) do |form| %>

  <% if crypted_note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(crypted_note.errors.count, "error") %> prohibited this crypted_note from being saved:</h2>

      <ul>
        <% crypted_note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%# unless crypted_note.persisted? %>
    <%= form.label :query, "Title:" %><br/>
    <%= form.text_field :description %>
    <div class="text-xs mt-2">Title will be visible to shared contacts and will be stored on our servers unencrypted</div>
    <br/>

  <div data-crypted-note-target="rawContentContainer">
    <%= form.label :crypted_note_raw_content, "Secret Content:" %><br/>

    <div data-controller="mask-textarea">
      <textarea 
        id="crypted_note_raw_content"
        data-controller="textarea-auto-resize"
        data-crypted-note-target="rawContent"
        data-mask-textarea-target="input"
        data-action="input->crypted-note#tryToEncrypt blur->mask-textarea#hide focus->mask-textarea#show input->textarea-auto-resize#resize" 
        style="min-height: 120px"></textarea> <!-- name attribute should not be saved in order to not set it to server -->
      <%= render "hide_show", controller_type: "textarea" %>
    </div>

    <div class="text-xs mt-2">Secret content will be stored on <em>DecLegacy</em> encrypted. Confidants will be able decrypt it if you become unresponsive. Unencrypted value is not sent to or stored on our server.</div>
    <br/>
  </div>
  <%# end %>

  <%= render "password_fields", type: :crypted_note, form: form, show_password_strength: !@crypted_note.persisted? %>
  <div class="text-xs mt-2">Encryption password is not sent or stored to our servers. If you loose your password or if your selected contacts will loose it, it will be impossible to decrypt secured content. We allow you to validate if selected contacts know encryption password without giving them ability to decrypt the content.</div>
  <br/>

  <div data-crypted-note-target="generatedContentContainer">
    <div data-crypted-note-target="generatedContentLinkContainer">
      <a href="#" data-action="click->crypted-note#showGeneratedContentFields">Show encrypted contents</a>
      <div class="text-xs mt-1 mb-4">Encrypted content which will be saved on DecLeagacy and sent to your email which allows you to retreive the secret without DecLegacy.</div>

    </div>

    <div data-crypted-note-target="generatedContentFieldsContainer" style="display:none">
      <%#= form.label :query, "Crypted Content:" %>
      <%= form.hidden_field :crypted_content, readonly: true, data: {crypted_note_target: :cryptedContent} %>
      
      <div data-crypted-note-target="codeTemplate" style="display:none"><%= code_block do render "executable_code"; end%></div>
      
      <label>Decryption JavaScript: </label>
      <div data-crypted-note-target="generatedDecryptionCode"></div>

      <div class="text-xs mt-2">
        We will send you a copy of this snippet to your email. This allows you to retreive the secret without DecLegacy.<br/><br/>
        <%= render "code_block_instructions" %>
      </div>
      
      <br/>
    </div>
  </div>

  <% if crypted_note.user == current_user %>
  <div data-crypted-note-target="submitContainer">
    <%= form.submit "Save" %>
  </div>
  <% end %>
<% end %>

app/views/crypted_notes/_hide_show.html.erb
<a style="position:absolute; margin-top: 10px; margin-left: 10px" href="#" data-action="click->mask-<%= controller_type %>#toggle">
  <span data-mask-<%= controller_type %>-target="show">
    <%= inline_svg('password-show') %>
  </span>
  <span data-mask-<%= controller_type %>-target="hide">
    <%= inline_svg('password-hide') %>
  <span>  
</a>

app/views/crypted_notes/_password_fields.html.erb
  <% type = type.to_s %>

  <%= form.label :crypted_note_encryption_password, "Encryption Password:" %><br/>
  <div data-controller="mask-password<% if defined?(show_password_strength) && show_password_strength %> password-strength<% end %>">
    <div>
      <input 
        autocomplete="off" 
        autofill="off" 
        id="crypted_note_encryption_password" 
        data-<%= type.dasherize %>-target="encryptionPassword" 
        data-password-strength-target="password"
        data-mask-password-target="input"
        data-action="input-><%= type.dasherize %>#onPasswordInput input->password-strength#onInput" 
        type="text" style="-webkit-text-security: circle;"
        />
      <%= render "crypted_notes/hide_show", controller_type: "password" %>
    </div>


    <div data-password-strength-target="result" class="text-green-500 text-red-500 mt-2 text-sm"></div>
  
    <div data-<%= type.dasherize %>-target="errorContent" style="display:none;">
      <div class="flex items-center p-4 mb-4 mt-2 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400" role="alert">
        <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
        </svg>
        <span class="sr-only">Info</span>
        <div>
          <span class="font-medium">Wrong password!</span> Please try different password.
        </div>
      </div>
    </div>
  </div>

  <%= form.hidden_field "short_password_hash",  data: {"#{type}_target" => "shortPasswordHash"} %>

app/views/crypted_notes/_warning.html.erb
<div id="alert-additional-content-2" class="alert p-4 mb-4 text-red-800 border border-red-300 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400 dark:border-red-800" role="alert">
  <div class="flex items-center">
    <svg class="flex-shrink-0 w-4 h-4 me-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
    </svg>
    <span class="sr-only">Info</span>
    <h3 class="text-lg font-medium !mb-0">Alert!</h3>
  </div>
  <div class="mt-2 mb-4 text-sm">
    <%= yield %>
  </div>
</div>

app/views/crypted_notes/edit.html.erb
<h1>Decrypt and Reveal the Secret</h1>

<%= render "form", crypted_note: @crypted_note %>

<br>

<div>
  <%= link_to "Back to crypted notes", crypted_notes_path %>
</div>

app/views/crypted_notes/index.html.erb
<% if @crypted_notes.any? %>
  <h1>Your Secrets</h1>
  <%= render "crypted_notes", crypted_notes: @crypted_notes %>
<% end %>

<% if @shared_crypted_notes.any? %>
  <h1>Secrets from Others</h1>
  <%= render "crypted_notes", crypted_notes: @shared_crypted_notes %>
<% end %>

<% if @crypted_notes.empty? && @shared_crypted_notes.empty? %>
  <h1>Welcome to DecLegacy</h1>
  <div>
    You don't have any secrets. Let's create the first one!
  </div>
<% end %>

<div class="mt-8">
  <%= link_to "Create New Secret", new_crypted_note_path, class: "btn-primary" %>
</div>

app/views/crypted_notes/new.html.erb
<h1>Create New Secret</h1>

<%= render "form", crypted_note: @crypted_note %>

<br>

<div>
  <%= link_to "Back to Secrets", crypted_notes_path %>
</div>

app/views/crypted_notes/show.html.erb
<%= @crypted_note.description %>


<div>
  <%#= link_to "Edit this crypted note", edit_crypted_note_path(@crypted_note) %> 
  <%= link_to "Back to crypted notes", crypted_notes_path %>

  <%#= button_to "Destroy this crypted note", @crypted_note, method: :delete %>
</div>