config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    root to: "crypted_notes#index", as: :authenticated_root

    resources :crypted_notes do
      resources :permitted_contacts do
        get "verify"
        patch "verify_update", to: "verify_update"
        post "request_access", to: "request_access"
        post "reject_access", to: "reject_access"
        get "reject_access"
        post "approve_access", to: "approve_acces"
      end
    end
  end

  get "/crypted_notes/*whatever", to: redirect("/users/sign_in")
  root to: redirect("/users/sign_in")
end

app/models/permitted_contact.rb
class PermittedContact < ApplicationRecord
  belongs_to :crypted_note
  validates :email, format: {with: Devise.email_regexp}

  def request_for_access!
    update!(
      decrypt_access_requested_at: Time.now,
      decrypt_access_granted_at: Time.now + auto_grant_decrypt_permission_in_x_days_after_the_request.days
    )
  end

  def reject_access!
    update!(
      decrypt_access_requested_at: nil,
      decrypt_access_granted_at: nil,
      decrypt_access_rejected_at: Time.now
    )
  end

  def approve_access!
    update!(
      decrypt_access_granted_at: Time.now,
      decrypt_access_rejected_at: nil
    )
  end

  def can_decrypt?
    true if decrypt_access_granted_at && decrypt_access_granted_at < Time.now
  end

  def verified_password?
    verified_password_at
  end
end

app/controllers/permitted_contacts_controller.rb
class PermittedContactsController < ApplicationController
  before_action :set_crypted_note, except: [:verify, :verify_update, :request_access]
  before_action :set_crypted_note_for_permitted_contact, only: [:verify, :verify_update, :request_access]
  before_action :set_permitted_contact, only: %i[show edit update destroy reject_access approve_access]

  # GET /permitted_contacts
  def index
    @permitted_contacts = @crypted_note.permitted_contacts
  end

  # GET /permitted_contacts/1
  def show
  end

  # GET /permitted_contacts/new
  def new
    @permitted_contact = PermittedContact.new
  end

  # GET /permitted_contacts/1/edit
  def edit
  end

  # POST /permitted_contacts
  def create
    @permitted_contact = @crypted_note.permitted_contacts.new(permitted_contact_params)

    if @permitted_contact.save
      CryptedNoteMailer.grant_permission_email(@permitted_contact).deliver_later

      redirect_to crypted_note_permitted_contacts_path, notice: "Permitted contact was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /permitted_contacts/1
  def update
    if @permitted_contact.update(permitted_contact_params)
      redirect_to crypted_notes_path, notice: "Permitted contact was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /permitted_contacts/1
  def destroy
    @permitted_contact.destroy
    redirect_to crypted_note_permitted_contacts_url(@crypted_note), notice: "Permitted contact was successfully destroyed.", status: :see_other
  end

  def verify
  end

  def verify_update
    if params[:permitted_contact][:has_verified_password]
      @permitted_contact.update!(verified_password_at: Time.now)
    end

    redirect_to root_path, notice: "You successfully verifed the password"
  end

  def request_access
    @permitted_contact.request_for_access!

    CryptedNoteMailer.request_access_email(@permitted_contact).deliver_later

    redirect_to root_path, notice: "We have requested decrypt request. If person will not reject the request until #{@permitted_contact.decrypt_access_granted_at.to_date}, you will be granted decrypt access automatically."
  end

  def reject_access
    @permitted_contact.reject_access!

    redirect_to root_path, notice: "Access to the secret for #{@permitted_contact.email} has been rejected"
  end

  def approve_access
    @permitted_contact.approve_access!

    redirect_to root_path, notice: "Access to the secret for #{@permitted_contact.email} has been granted"
  end

  private

  def set_crypted_note
    @crypted_note = current_user.crypted_notes.find(params[:crypted_note_id])
  end

  def set_crypted_note_for_permitted_contact
    @permitted_contact = PermittedContact.find_by(email: current_user.email, id: params[:permitted_contact_id], crypted_note_id: params[:crypted_note_id])
    @crypted_note = @permitted_contact.crypted_note
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_permitted_contact
    @permitted_contact = @crypted_note.permitted_contacts.find(params[:id] || params[:permitted_contact_id])
  end

  # Only allow a list of trusted parameters through.
  def permitted_contact_params
    params.require(:permitted_contact).permit(:email, :auto_grant_decrypt_permission_in_x_days_after_the_request)
  end
end

app/helpers/permitted_contacts_helper.rb
module PermittedContactsHelper
end

app/views/permitted_contacts/_form.html.erb
<%= form_with(model: [crypted_note, permitted_contact]) do |form| %>
  <% if permitted_contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(permitted_contact.errors.count, "error") %> prohibited this permitted_contact from being saved:</h2>

      <ul>
        <% permitted_contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %><br/><br/>

    <%= form.label :auto_grant_decrypt_permission_in_x_days_after_the_request %><br/>
    <%= form.text_field :auto_grant_decrypt_permission_in_x_days_after_the_request%>
  </div>

  <br/>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/permitted_contacts/_permitted_contact.html.erb
<div id="<%= dom_id permitted_contact %>">
  <div class="flex -m-4 mb-4 bg-slate-200 text-slate-500 rounded-t p-4">
    <div class="flex-grow">
      <h3 class="mb-0"><%= permitted_contact.email %></h3>
    </div>
    <div class="">
      <%= link_to "Edit", edit_crypted_note_permitted_contact_path(@crypted_note, permitted_contact), class: "btn" %>
    </div>
  </div>

  

  <% if permitted_contact.verified_password? %>
    <%= render 'shared/alert', color: 'green', title: "Success", content: "Successfully verified that he knows encryption password on #{l permitted_contact.verified_password_at.to_date}" %>
  <% else %>
    <%= render 'shared/alert', color: 'orange', title: "Success", content: "User have not yet verified that he knows the encryption password" %>
  <% end %>

  <% if permitted_contact.decrypt_access_granted_at %> 
    <% if permitted_contact.decrypt_access_granted_at < Time.now %>
      <%= render 'shared/alert', color: 'red', title: "Success", content: "User is allowed to decrypt the content" %>
    <% else %>
      <%= render 'shared/alert', color: 'red', title: "Success", content: "User will be granted with access on #{l(permitted_contact.decrypt_access_granted_at.to_date)}" %>
    <% end %>
  <% else %>
    <%= render 'shared/alert', color: 'blue', title: "Success", content: "Confidant have not yet requested access to your secrets. Access will be granted #{permitted_contact.auto_grant_decrypt_permission_in_x_days_after_the_request} days after the request." %>
  <% end  %>

 
</div>

app/views/permitted_contacts/edit.html.erb
<h1>Editing permitted contact</h1>

<%= render "form", permitted_contact: @permitted_contact, crypted_note: @crypted_note %>

<br>

<div>
  <%= link_to "Back to permitted contacts", crypted_note_permitted_contacts_path(@crypted_note) %>
</div>

app/views/permitted_contacts/index.html.erb
<h1>Permitted contacts</h1>

<div id="permitted_contacts" class="box-list">
  <% @permitted_contacts.each do |permitted_contact| %>
    <div class="box-list-item">
      <%= render permitted_contact %>
    </div>
  <% end %>
</div>

<br/>

<%= link_to "New permitted contact", new_crypted_note_permitted_contact_path(@crypted_note), class: "btn-primary" %>

app/views/permitted_contacts/new.html.erb
<h1>New permitted contact</h1>

<%= render "form", permitted_contact: @permitted_contact, crypted_note: @crypted_note %>

<br>

<div>
  <%= link_to "Back to permitted contacts", crypted_note_permitted_contacts_path(@crypted_note) %>
</div>

app/views/permitted_contacts/show.html.erb
<%= render @permitted_contact %>

<div>
  <%= link_to "Edit this permitted contact", edit_permitted_contact_path(@permitted_contact) %> |
  <%= link_to "Back to permitted contacts", permitted_contacts_path %>

  <%= button_to "Destroy this permitted contact", @permitted_contact, method: :delete %>
</div>

app/views/permitted_contacts/verify.erb
<% 
  crypted_note = @crypted_note 
  permitted_contact = @permitted_contact
%>

<h1>Vefify that you know password to decrypt the content</h1>

<%= form_with(model: [crypted_note, permitted_contact], url: crypted_note_permitted_contact_verify_update_path(crypted_note, permitted_contact), data: {controller: 'verify', verify_short_password_hash_value: @crypted_note.short_password_hash}) do |form| %>
  <%= render "crypted_notes/password_fields", type: :verify, form: form %>

  <%= form.hidden_field "has_verified_password",  data: { verify_target: "hasVerifiedPassword"} %>

  <div class="mt-4">
    <%= form.submit "Verify password", data: { action: "verify#onSubmit:prevent"} %>
  </div>
<% end %>